In [5]:
!pip install uncertainties

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [8]:
import numpy as np
from uncertainties import ufloat

#INTERFERENCIA 1 (2,3,4,5 RANURAS, MISMA d)

d1=0.125 #mm
R=np.array([400,300,200]) #mm

#1RA MEDICION
y40_1=np.array([4,4,4,4]) #mm

#2DA MEDICION
y30_1=np.array([3,3,3,3]) #mm

#3RA MEDICION
y20_1=np.array([2,2,2,2]) #mm


#RESULTADOS 1
longOnda40_1 = (d1/(R[0]*2))*y40_1
print(longOnda40_1)
longOnda30_1 = (d1/(R[1]*2))*y30_1
print(longOnda30_1)
longOnda20_1 = (d1/(R[2]*2))*y20_1
print(longOnda20_1)


print('-------------------------------------------------')



#INTERFERENCIA (2 RANURAS DIFERENTES d)

d2=np.array([0.250,0.5,0.250,0.5]) #mm
R=np.array([400,300,200]) #mm
y2=np.array([[5,0,2,0],[3,0,2,0],[0,0,0,0]]) #todos los 0 son de prueba
m=np.array([[5,1,2,1],[4,1,2,1],[1,1,1,1]])  #todos los 1 son de prueba


#TODAS LAS MEDICIONES ()

longOnda40_2_Def=[]
print('datos:')
for i in range(3):
    print(f'R{i}= {R[i]}')
    for j in range(4):
        print(f'm{i}{j}= {m[i][j]}')
        print(f'd2{j}= {d2[i]}')
        print(f'y2{i}{j}= {y2[i][j]}')

        longOnda40_2=d2[j]*y2[i][j]/(m[i][j]*R[i])
        longOnda40_2_Def= np.append(longOnda40_2_Def,longOnda40_2)
        
    print('-------------------------------------------------')
print(longOnda40_2_Def)


print('-------------------------------------------------')
#DIFRACCION


a=[0.02,0.04,0.08,0.16]
R=[400,300,200]
y3=[[10,5,2.5,1],[9,4,2,1.5],[5,2.5,1.5,0.5]]

#for i in range(4):
 #   for j in range(3):
  #      longOnda_3 = 

[0.000625 0.000625 0.000625 0.000625]
[0.000625 0.000625 0.000625 0.000625]
[0.000625 0.000625 0.000625 0.000625]
-------------------------------------------------
datos:
R0= 400
m00= 5
d20= 0.25
y200= 5
m01= 1
d21= 0.25
y201= 0
m02= 2
d22= 0.25
y202= 2
m03= 1
d23= 0.25
y203= 0
-------------------------------------------------
R1= 300
m10= 4
d20= 0.5
y210= 3
m11= 1
d21= 0.5
y211= 0
m12= 2
d22= 0.5
y212= 2
m13= 1
d23= 0.5
y213= 0
-------------------------------------------------
R2= 200
m20= 1
d20= 0.25
y220= 0
m21= 1
d21= 0.25
y221= 0
m22= 1
d22= 0.25
y222= 0
m23= 1
d23= 0.25
y223= 0
-------------------------------------------------
[0.000625   0.         0.000625   0.         0.000625   0.
 0.00083333 0.         0.         0.         0.         0.        ]
-------------------------------------------------


In [6]:
d2=np.array([0.250,0.5,0.25,0.5]) #mm
R=np.array([400,300,200]) #mm
y2=np.array([[5,2,2,3],[3,3,2,3],[2,3,3,4]])
m=np.array([[5,2,2,2],[4,2,2,3],[2,2,2,3]])

In [5]:
print(m[1][2])
lamb1=[]

for i in range(3):
    for j in range(4):
        print(f'm{i}{j}= {m[i][j]}')
        lamb= d2[j]*y2[i][j]/(m[i][j]*R[i])
        lamb1 = np.append(lamb1,lamb)
        
print(np.array(lamb1))



2
m00= 5
m01= 2
m02= 2
m03= 2
m10= 4
m11= 2
m12= 2
m13= 3
m20= 2
m21= 2
m22= 2
m23= 3
[0.000625   0.00125    0.000625   0.001875   0.000625   0.0025
 0.00083333 0.00166667 0.00125    0.00375    0.001875   0.00333333]


In [16]:
#Cálculo de error 
delta_y = 0.5 #mm
delta_R = 0.5 #mm
delta_d1 = 0.01 #mm
#INTERFERENCIA 1 (2,3,4,5 RANURAS, MISMA d)

d1=0.125 #mm
R=np.array([400,300,200]) #mm

#1RA MEDICION
y40_1=np.array([4,4,4,4]) #mm

#2DA MEDICION
y30_1=np.array([3,3,3,3]) #mm

#3RA MEDICION
y20_1=np.array([2,2,2,2]) #mm


#RESULTADOS 1
longOnda40_1 = (d1/(R[0]*2))*y40_1
print(longOnda40_1)
longOnda30_1 = (d1/(R[1]*2))*y30_1
print(longOnda30_1)
longOnda20_1 = (d1/(R[2]*2))*y20_1
print(longOnda20_1)


#error de la longitud calculada por la interferencia (2,3,4,5)
delta_Long_40 = np.sqrt((4/(2*400)*delta_d1)**2 + (4*d1/(2*400**2)*delta_R)**2 + (d1/(2*400)*delta_y)**2)
print(f'error longitud a 40cm {delta_Long_40}')
delta_Long_30 = np.sqrt((3/(2*300)*delta_d1)**2 + (3*d1/(2*300**2)*delta_R)**2 + (d1/(2*300)*delta_y)**2)
print(f'error longitud a 30cm {delta_Long_30}')
delta_Long_20 = np.sqrt((2/(2*200)*delta_d1)**2 + (2*d1/(2*200**2)*delta_R)**2 + (d1/(2*200)*delta_y)**2)
print(f'error longitud a 20cm {delta_Long_20}')

[0.000625 0.000625 0.000625 0.000625]
[0.000625 0.000625 0.000625 0.000625]
[0.000625 0.000625 0.000625 0.000625]
error longitud a 40cm 9.275842806215778e-05
error longitud a 30cm 0.00011554990053604068
error longitud a 20cm 0.0001640625


In [87]:
#INTERFERENCIA 1 (2,3,4,5 RANURAS, MISMA d)

d1=ufloat(0.125,0.125*0.05) #mm
R1=np.array([400,300,200]) #mm
#m = 2 en todos

y1=np.array([[4,4,4,4],[3,3,3,3],[2,2,2,2]]) #mm

# Incertidumbres de las mediciones (los valores de d tienen un error del 5%)
delta_y = 0.5
delta_R = 0.5

# Definición de las variables con sus incertidumbres

R1_array = np.array([ufloat(400, delta_R), ufloat(300, delta_R), ufloat(200, delta_R)])
y1_array = np.array([[ufloat(4, delta_y),ufloat(4, delta_y),ufloat(4, delta_y),ufloat(4, delta_y)],[ufloat(3, delta_y),ufloat(3, delta_y),ufloat(3, delta_y),ufloat(3, delta_y)],[ufloat(2, delta_y),ufloat(2, delta_y),ufloat(2, delta_y),ufloat(2, delta_y)]])


longOnda_1_Def_u=[]

for i in range(3):
    for j in range(4):
        longOnda_1=d1*y1_array[i][j]/(2*R1_array[i])
        longOnda_1_Def_u= np.append(longOnda_1_Def_u,longOnda_1)

for k, longitud_onda in enumerate(longOnda_1_Def_u):
    print(f'La longitud de onda correspondiente a la medicion {k+1}, calculada utilizando propagacion del error, es de:{longitud_onda}')

La longitud de onda correspondiente a la medicion 1, calculada utilizando propagacion del error, es de:0.00063+/-0.00008
La longitud de onda correspondiente a la medicion 2, calculada utilizando propagacion del error, es de:0.00063+/-0.00008
La longitud de onda correspondiente a la medicion 3, calculada utilizando propagacion del error, es de:0.00063+/-0.00008
La longitud de onda correspondiente a la medicion 4, calculada utilizando propagacion del error, es de:0.00063+/-0.00008
La longitud de onda correspondiente a la medicion 5, calculada utilizando propagacion del error, es de:0.00063+/-0.00011
La longitud de onda correspondiente a la medicion 6, calculada utilizando propagacion del error, es de:0.00063+/-0.00011
La longitud de onda correspondiente a la medicion 7, calculada utilizando propagacion del error, es de:0.00063+/-0.00011
La longitud de onda correspondiente a la medicion 8, calculada utilizando propagacion del error, es de:0.00063+/-0.00011
La longitud de onda correspondie

In [82]:
#INTERFERENCIA 2 (2,2,2,2 RANURAS, DISTINTA d)

d2=np.array([0.250,0.5,0.250,0.5]) #mm
#R=np.array([400,300,200]) #mm
#y2=np.array([[5,0,2,0],[3,0,2,0],[0,0,0,0]]) #todos los 0 son de prueba
#m=np.array([[5,1,2,1],[4,1,2,1],[1,1,1,1]])  #todos los 1 son de prueba

# Incertidumbres de las mediciones (los valores de d tienen un error del 5%)
delta_y = 0.5
delta_R = 0.5

# Definición de las variables con sus incertidumbres
d2_array = []

for g in range(4):
    uf = ufloat(d2[g], d2[g]*0.05)
    d2_array = np.append(d2_array, uf)

R2_array = np.array([ufloat(400, delta_R), ufloat(300, delta_R), ufloat(200, delta_R)])
y2_array = np.array([[ufloat(5, delta_y),ufloat(0, delta_y),ufloat(2, delta_y),ufloat(0, delta_y)],[ufloat(3, delta_y),ufloat(0, delta_y),ufloat(2, delta_y),ufloat(0, delta_y)],[0,0,0,0]])
m2_array = np.array([[5,1,2,1],[4,1,2,1],[1,1,1,1]])

longOnda_2_Def_u=[]

for i in range(3):
    for j in range(4):
        longOnda_2=d2_array[j]*y2_array[i][j]/(m2_array[i][j]*R2_array[i])
        longOnda_2_Def_u= np.append(longOnda_2_Def_u,longOnda_2)

for k, longitud_onda in enumerate(longOnda_2_Def_u):
    print(f'La longitud de onda correspondiente a la medicion {k+1}, calculada utilizando propagacion del error, es de:{longitud_onda}')

La longitud de onda correspondiente a la medicion 1, calculada utilizando propagacion del error, es de:0.00063+/-0.00007
La longitud de onda correspondiente a la medicion 2, calculada utilizando propagacion del error, es de:0.0000+/-0.0006
La longitud de onda correspondiente a la medicion 3, calculada utilizando propagacion del error, es de:0.00063+/-0.00016
La longitud de onda correspondiente a la medicion 4, calculada utilizando propagacion del error, es de:0.0000+/-0.0006
La longitud de onda correspondiente a la medicion 5, calculada utilizando propagacion del error, es de:0.00063+/-0.00011
La longitud de onda correspondiente a la medicion 6, calculada utilizando propagacion del error, es de:0.0000+/-0.0008
La longitud de onda correspondiente a la medicion 7, calculada utilizando propagacion del error, es de:0.00083+/-0.00021
La longitud de onda correspondiente a la medicion 8, calculada utilizando propagacion del error, es de:0.0000+/-0.0008
La longitud de onda correspondiente a la

In [76]:
#DIFRACCION

#MEDICIONES (m siempre es 1)
a=[0.02,0.04,0.08,0.16]
R3=[400,300,200]
#y3=np.array([[10,5,2.5,1],[9,4,2,1.5],[5,2.5,1.5,0.5]])

y3 = np.array([[12.5,6,3,1.5],[9,4.5,2.5,1.5],[6,3,1.5,1]]) #mitad de la distancia entre los primeros minimos por izquierda y derecha
#ERRORES (los valores de a tienen un error del 5%)
delta_y3 = 0.5
delta_R3 = 5

a_array = []
R3_array = []
longOnda_3_Def_u = []

for t in range(4):
    uf_a = ufloat(a[t], a[t]*0.05)
    a_array = np.append(a_array, uf_a)
    
for n in range(3):    
    uf_R = ufloat(R3[n], delta_R3)
    R3_array = np.append(R3_array, uf_R)

y3_ufloat = np.zeros(y3.shape, dtype=object)
for i in range(y3.shape[0]):
    for j in range(y3.shape[1]):
        y3_ufloat[i, j] = ufloat(y3[i, j], delta_y3)    
    
for w in range(3):
    for v in range(4):
        longOnda_3=a_array[v]*y3_ufloat[w][v]/R3_array[w]
        longOnda_3_Def_u= np.append(longOnda_3_Def_u,longOnda_3)


for k, longitud_onda in enumerate(longOnda_3_Def_u):
    print(f'La longitud de onda correspondiente a la medicion {k+1}, calculada utilizando propagacion del error, es de:{longitud_onda}')

La longitud de onda correspondiente a la medicion 1, calculada utilizando propagacion del error, es de:0.00063+/-0.00004
La longitud de onda correspondiente a la medicion 2, calculada utilizando propagacion del error, es de:0.00060+/-0.00006
La longitud de onda correspondiente a la medicion 3, calculada utilizando propagacion del error, es de:0.00060+/-0.00010
La longitud de onda correspondiente a la medicion 4, calculada utilizando propagacion del error, es de:0.00060+/-0.00020
La longitud de onda correspondiente a la medicion 5, calculada utilizando propagacion del error, es de:0.00060+/-0.00005
La longitud de onda correspondiente a la medicion 6, calculada utilizando propagacion del error, es de:0.00060+/-0.00007
La longitud de onda correspondiente a la medicion 7, calculada utilizando propagacion del error, es de:0.00067+/-0.00014
La longitud de onda correspondiente a la medicion 8, calculada utilizando propagacion del error, es de:0.00080+/-0.00027
La longitud de onda correspondie

In [90]:
print(0.125*0.05)

0.00625
